resources:
  - type: Game
    path: /api/games
    operations: [list, retrieve, create, update, delete]
    fields:
      - name: title
        type: string
        required: true
        query: true
      - name: date_released
        type: date
        query: true
        required: true
      - name: photo
        type: image_url
        required: true
      - name: total_units_sold
        type: number
        query: true
        required: true
    permissions:
      list: public
      retrieve: public
      create: admin
      update: admin
      delete: admin

  - type: Weapon
    path: /api/weapons
    operations: [list, retrieve, create, update, delete]
    fields:
      - name: weapon
        type: string
        required: true
      - name: image
        type: image_url
        #required: true
    permissions:
      list: public
      retrieve: public
      create: admin
      update: admin
      delete: admin

  - type: Monster
    path: /api/monsters
    operations: [list, retrieve, create, update, delete]
    fields:
      - name: monster
        type: string
        required: true
      - name: image
        type: image_url
        #required: true
      - name: game_id
        type: integer
        required: true
    permissions:
      list: public
      retrieve: public
      create: admin
      update: admin
      delete: admin

  - type: Hunt
    path: /api/hunts
    operations: [list, retrieve, create, update, delete]
    fields:
      - name: time_seconds
        type: integer
        required: true
      - name: weapon
        type: Weapon
        required: true
      - name: weapon_source_monster
        type: Monster
        required: true
      - name: monster
        type: Monster
        required: true
      - name: rank
        type: string
        choices: [Low, High, G]
        required: true
      - name: game
        type: Game
        required: true
        query: true
    permissions:
      list: public
      retrieve: public
      create: user
      update: owner
      delete: [owner,admin]
